name: manukpos
description: Aplikasi Point of Sale untuk UMKM Indonesia yang praktis, handal, dan terjangkau.
homepage:
repository: https://github.com/Yasminingrum/manukpos

# Project version
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Keamanan
  crypto: ^3.0.3
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.0.0

  # UI Components
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.4
  intl: ^0.19.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  cached_network_image: ^3.3.0
  fl_chart: ^0.71.0
  flutter_slidable: ^4.0.0

  # State Management
  provider: ^6.1.1
  equatable: ^2.0.5

  # Database
  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # Network
  dio: ^5.3.3
  connectivity_plus: ^6.1.3
  
  # Data Handling
  json_annotation: ^4.8.1
  freezed_annotation: ^3.0.0

  # Bluetooth untuk printer
  flutter_bluetooth_serial: ^0.4.0
  
  # Barcode & QR
  mobile_scanner: ^3.5.5
  qr_flutter: ^4.1.0
  
  # PDF & Print
  printing: ^5.11.0
  pdf: ^3.10.6
  
  # Export & Import
  excel: ^2.1.0
  archive: ^3.3.0
  
  # Utility
  uuid: ^4.1.0
  logger: ^2.0.2+1
  permission_handler: ^12.0.0+1
  package_info_plus: ^8.3.0
  device_info_plus: ^11.3.3
  image_picker: ^1.0.4
  url_launcher: ^6.2.1
  share_plus: ^10.1.4
  image: ^4.1.3
  http: ^1.1.0 

  # Firebase
  firebase_core: ^2.15.0
  firebase_analytics: ^10.7.0
  firebase_crashlytics: ^3.4.9
  firebase_remote_config: ^4.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^3.0.6
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.5

# Flutter configuration
flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

# Flutter icons configuration
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

# Flutter native splash screen
flutter_native_splash:
  color: "#607D8B"
  image: "assets/images/splash_logo.png"
  android: true
  ios: true